# LeeesBungeeQueue V4.3.0
#make sure to follow the tutorial on the github
#it tells you everything you need to do
#https://github.com/XeraPlugins/LeeesBungeeQueue


#IMPORTANT DO THIS FIRST
#these are all the important configuration
#options that you should do first in order
#to have the plugin work properly

#this is the queue server where players
#will wait to be put on the main server
QUEUESERVER: "queue"
#make this the name of the main server
#where the players play on etc
MAINSERVER: "7b7t"
#set this to false if your a premium server
#premium means online mode using mojangs authentication
ENABLEAUTHSERVER: "true"
AUTHSERVER: "auth"
#server to send the players to after queue
AFTERQUEUE: "auth"
#Max players allowed onto main server
#before the queue is triggered
MAINSERVERSLOTS: 230


#Username regex
REGEX: "[a-zA-Z0-9_]*"

#Server is full message
SERVERISFULLMESSAGE: "&67b7t is full"


#Position in queue message by default only sends in chat every 10 seconds
#you can have it on the hotbar by setting POSITIONMESSAGEHOTBAR: "false" to true
POSITIONMESSAGEHOTBAR: "false"
QUEUEPOSITION: "&6Position in queue: &l<position>"
ENABLEKICKMESSAGE: "false"
KICKMESSAGE: "&6You have lost connection to the server"
SERVERDOWNKICKMESSAGE: "&b7b&37t &6is down please try again later :("


#set this to false if you want it to kick players from the
#server when the main server goes down
#if its set to true itll pause the queue and let players
#rejoin and wait in queue until the main server is online
CONNECTTOQUEUEWHENDOWN: "true"


#this shows the queue size when you hover over the ping on the server list
SERVERPINGINFOENABLE: "true"
SERVERPINGINFO:
  - "&b7b&37t &6Queue Info"
  - "&6Priority: &l%priority%"
  - "&6Regular: &l%regular%"
  - "&6Total in queue: &l%totalinqueue%"
  - "&6Max players: &l%maxplayers%"
CUSTOMPROTOCOL: "&b7b&37t &61.8.x to 1.17.x"
ENABLEMOTD: "true"
MOTD: "&b7b&37t &6Queue Size: Prio: &l%priosize% &6Reg: &l%regsize% &6Total: &l%total% &6Max: &l%maxplayers%"
ENABLERANDOMMOTD: "true"
RANDOMMOTDS:
  - "&b7b&37t &6LICK MY BALLS Regular: &l%regsize%"
  - "&b7b&37t &6fuck you cunt Priority: &l%priosize%"
  - "&b7b&37t &6If you lag or crash my server i will kill you im not joking - Leee"
  - "&b7b&37t &6wwe dupe"
  - "&b7b&37t &62l2c.org"
  - "&b7b&37t &6hola españoles"
  - "&b7b&37t &6[User] is now an operator"
  - "&b7b&37t &6ñññññññññññ"
  - "&b7b&37t &6?"
  - "&b7b&37t &6minecraft r34 sex dupe added!"
  - "&b7b&37t &6NightmareZ is really a Nightmare"
  - "&b7b&37t &6qbasty is (insert insult here)"
  - "&b7b&37t &6SEXOOOO 7b7t on top"
  - "&b7b&37t &6TFB IS go0d"
  - "&bTCPShield bandwidth limit reached Upgrade at tcpshield.com"
  - "&b7b&37t &6Leee has schizophrenia - nigtardo69"
  - "&b7b&37t &6sorry but lee is gay so you are unable to connect to this server"
  - "&b7b&37t &62b2t sucks, join 7b7t!!11"
  - "&b7b&37t &6admin password is : Admin12345 Admin12345"
  - "&b7b&37t &6map reset in 23 minutes"
  - "&b7b&37t &6consume the piss chalice"
  - "&b7b&37t &6i like having kids"
  - "&4cannot connect to server"
  - "&b7b&37t &6ok this is me this is my own piss"
  - "&b7b&37t &6i like abandoning my wife and kids for 1 dollar"
  - "&b7b&37t &6I am Mirillis member i am stupid"
  - "&b7b&37t &6if u see this gay"
  - "&b7b&37t &6leee please say SEXOOOO"
  - "&b7b&37t &6i like kids"
  - "&b7b&37t &6I hate drivr3joe"
  - "&b7b&37t &6Fucking newfags in 0 0 since 2021"
  - "&b7b&37t &6254n_m=GOD"
  - "&b7b&37t &6Obama Hamburger sussy balls"
  - "&b7b&37t &6join today for free kits and bitches!"
  - "&b7b&37t &6my dad said i was drunk so i said i am a sussy baka"
  - "&b7b&37t &6Cord of my base -34546 45 34457"
  - "&b7b&37t &6Your a hoe."
  - "&b7b&37t &6who trades illegals? /msg"
  - "&b7b&37t &6imagine reading motds"
  - "&b7b&37t &6drink it all NOHOHOHO"
  - "&b7b&37t &6adquiere una monster es la nueva monster simon c mamo no olvides adquirir la nueva monster"
  - "&b7b&37t &6popbobsexdupe is real!!!!!!!!!!!"
  - "&b7b&37t &6BLACK CREEPER ON TOPA"
  - "&b7b&37t &6cpvp at 12 fps"
  - "&b7b&37t &6leee if u see this join vc"
  - "&b7b&37t &6it actually tastes surprisingly good!"
  - "&b7b&37t &6Pou owns u and all"
  - "&b7b&37t &6cpvp is beautiful"
  - "&b7b&37t &6Paper Airplane Go Zoooom"
  - "&b7b&37t &6lee has a minor addiction to buses and trains"
  - "&b7b&37t &6Crackers On Top!"


#Connecting to server message use <server> if you want it
#to just use the name of the default server
JOININGMAINSERVER: "&6Connecting to 7b7t..."


#set this to true if you wanna make the
#max players appear as whatever number you want
ENABLEQUEUESERVERSLOTS: "true"
QUEUESERVERSLOTS: 10000


#this feature is enabled by default
#it puts players in queue when they login
#to prevent mass raids from crashing your main
#server set to false to disable it
ALWAYSQUEUE: "true"


#Permissions
#in order for queue bypass to work any accounts with the permission
#must also not have priority queue if they have both the permissions
#it will confuse them and break the queue
QUEUEBYPASSPERMISSION: "queue.override"
QUEUEPRIORITYPERMISSION: "queue.priority"
ADMINPERMISSION: "queue.admin"


#Queue server tablist configuration use <position> to show the current position of the player
#and use <wait> to show the estimated wait time of t    he player(not very accurate yet)
#this only shows when your in the queue waiting to join use a separate plugin for your main server
HEADER: "\n&b7builders&37tools\n\n&67b7t is full\nPosition in queue: &l<position>\n&6Estimated time: &l<wait>\n"

FOOTER: "\n   &6You can now donate to receive priority queue status, please visit donate.7b7t.me   \n\n&7contact: nate@xera.ca\n
discussion: http://discord.7b7t.me\nwebsite: https://www.7b7t.me\nThese are the only official 7b7t websites and contacts\n"


#configs for priority queue tablist
HEADERPRIORITY: "\n&b7builders&37tools\n\n&67b7t is full\nPosition in queue: &l<position>\n&6Estimated time: &l<wait>\n"

FOOTERPRIORITY: "\n   &6You have priority queue status please wait for an available slot on the server   \n\n&7contact: nate@xera.ca\n
discussion: http://discord.7b7t.me\nwebsite: https://www.7b7t.me\nThese are the only official 7b7t websites and contacts\n"
