#LeeesBungeeQueue V5.2.0
#make sure to follow the tutorial on the github
#it tells you everything you need to do
#https://github.com/XeraPlugins/LeeesBungeeQueue


#IMPORTANT DO THIS FIRST
#these are all the important configuration
#options that you should do first in order
#to have the plugin work properly

#this is the queue server where players
#will wait to be put on the main server
QUEUESERVER: "queue"
#make this the name of the main server
#where the players play on etc
MAINSERVER: "8b8t"
#set this to false if your a premium server
#premium means online mode using mojangs authentication
ENABLEAUTHSERVER: "true"
AUTHSERVER: "auth"
#server to send the players to after queue
AFTERQUEUE: "auth"
#Max players allowed onto main server
#before the queue is triggered
MAINSERVERSLOTS: 230

#Antibot works by checking
#if player has permission
#antivpn.bypass if they do not have
#the permission they get kicked
#use this plugin to set up A
#antibot verification website:
#https://github.com/Leeewith3Es/LeeesWhitelistPlugin
#otherwise set this to false
ANTIBOT: "true"
ANTIBOTMESSAGE: "&6[&18builders&98tools&6]\nDisconnected for bot\nIf you are not a bot please visit &chttps://antibot.8b8t.me\n&6Si no eres un robot porfavor visita &chttps://antibot.8b8t.me"

#Username regex
REGEX: "[a-zA-Z0-9_]*"

#Server is full message
SERVERISFULLMESSAGE: "&68b8t is full"


#Position in queue message by default only sends in chat every 10 seconds
#you can have it on the hotbar by setting POSITIONMESSAGEHOTBAR: "false" to true
POSITIONMESSAGEHOTBAR: "false"
QUEUEPOSITION: "&6Position in queue: &l<position>"
ENABLEKICKMESSAGE: "false"
KICKMESSAGE: "&6You have lost connection to the server"
SERVERDOWNKICKMESSAGE: "&18b&98t &6is down please try again later :("


#set this to false if you want it to kick players from the
#server when the main server goes down
#if its set to true itll pause the queue and let players
#rejoin and wait in queue until the main server is online
CONNECTTOQUEUEWHENDOWN: "true"


#this shows the queue size when you hover over the ping on the server list
SERVERPINGINFOENABLE: "true"
SERVERPINGINFO:
  - "&18b&98t &6Queue Info"
  - "&6Priority: &l%priority%"
  - "&6Regular: &l%regular%"
  - "&6Total in queue: &l%totalinqueue%"
  - "&6Max players on main server: &l%maxplayers%"
  - "&6Donate to recieve priority queue at &chttps://donate.8b8t.me"
CUSTOMPROTOCOL: "&18b&98t &61.8.x to 1.19.x"
ENABLEMOTD: "true"
MOTD: "&18b&98t &6Queue Size: Prio: &l%priosize% &6Reg: &l%regsize% &6Total: &l%total% &6Max: &l%maxplayers%"
ENABLERANDOMMOTD: "true"
RANDOMMOTDS:
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &68t   &6Praise The Sun"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6mir is genius"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6El mismisimo Pablo emilio escobar"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6MirWasHere"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6do not talk to mir under any circumstances"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6this was cooler 1 year ago"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6firawft sucks"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6_Organik will find you, _Organik will kill you"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6I dont need kits, i need cats"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6onlypuppy7 likes to suck huge cock"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6n word"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &68b8t owns 6b6t!1!!"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6Jesse, necesitamos más crotolamo"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6fuck microsoft"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6Woofer"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6biden plays here"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6jesser where is the cocainer"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6insert very original motd here"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6free kit on 00"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6skeet skeet number uan chit"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &66b6t sucks"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6Hamburger"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6Osiris on top"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6RS on top"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6invite 2 skeet pls"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6Ohiocraft"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6https://www.youtube.com/watch?v=0hevhAHvY-A"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6RS have big pp"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6nixware sucks ass"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &68b8t #1 Anarchy server soon"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &cSr&aGokuto &fon &cY&fT"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6JustAndrea is taco women"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6BibleH4ck good"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6qbasty is gay"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6daynios on top!"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6pissmaster is a furry kek"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6your daily dose of autism can be found here!"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6buy donator for bedrock and illegal items"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6Leee got the white boy stare"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6Make 8b8t Great Again"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6Mir is better than cipher"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6where 32ks"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6free kits at 0 0"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6kill all furrys"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6stanlin exposed"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6I have cancer and severe autism"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6dont dm Smuki#6969"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6x: 103924 y: 53 z: 109"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6yesterday i was diagnosed with aids"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6kill all furrys ( that includes @Soaws  )"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6Don't dm Mir.#0001 at December 1 2022"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6how about we all stop fighting and we start building cocks"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6run leuxbackdoor 🤓"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &18b&b8b&f: &l&o&cThe merge biggest anarchy "
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6VENEZUELA ON TOP"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6DPS owns you"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6free owner if u join"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &68bee 8tee dot mi is the best minecraft server"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6LEEEXSTALIN"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6CHANGE THE SERVER PICTURE ITS BAD"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6danigod el ser mas inteligente del mundo"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6basic bitches join dps"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6Woofer is the best 8b8t player"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6just andrea is simp"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6grassers best group"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6let's buy 6b6t!"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6Mir is the best 8b8t pvper"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6Family Friendly Server"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6join mek gang"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6quit anarchy move to vanilla"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6any group other than dps on top"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6GRINGOS IGUEPUTAS"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6£€€€w!th3€€€"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &61.13+ is shit"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6Sweden, the best nation in the world idgf"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6join 8b8t discord server for free kits"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6give kurtz a dick"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6updated to 1.19"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6SOPLAMONDA"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6lAlekz best 7b player ever"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6join 8b8t discord to get friends"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6dont dm SamWithUke ✨#2357"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6CRACKERS came back"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6Woofer is the best 8b8t player ever"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6don't dm Mir at 8b8t discord server"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6CRACKERS CAME BACK"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6welcome to Ohio"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6i AM THE BESt!!!!111"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6mention#0001"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6I left my girlfriend so I could play 8b8t quietly."
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6i do not shower but i can crystal pvp!"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6im a free thinker, i make up situations in my head and instantly believe them"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6bird flu? yeah they tend to do that"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6Leee was here ;)"
  - "&18b                                            &a[1.8.x to 1.19.x]    &98t   &6suck my motherfucking dick -Infisrael#1337"

#Connecting to server message use <server> if you want it
#to just use the name of the default server
JOININGMAINSERVER: "&6Connecting to 8b8t..."


#set this to true if you wanna make the
#max players appear as whatever number you want
ENABLEQUEUESERVERSLOTS: "true"
QUEUESERVERSLOTS: 3000


#this feature is enabled by default
#it puts players in queue when they login
#to prevent mass raids from crashing your main
#server set to false to disable it
ALWAYSQUEUE: "true"


#Permissions
#in order for queue bypass to work any accounts with the permission
#must also not have priority queue if they have both the permissions
#it will confuse them and break the queue
QUEUEBYPASSPERMISSION: "queue.override"
QUEUEPRIORITYPERMISSION: "queue.priority"
ADMINPERMISSION: "queue.admin"


#Queue server tablist configuration use <position> to show the current position of the player
#and use <wait> to show the estimated wait time of t    he player(not very accurate yet)
#this only shows when your in the queue waiting to join use a separate plugin for your main server
HEADER: "\n&18builders&98tools\n\n&68b8t is full\nPosition in queue: &l<position>\n&6Estimated time: &l<wait>\n"

FOOTER: "\n   &6You can now donate to receive priority queue status, please visit donate.8b8t.me   \n\n&7contact: nate@xera.ca\n
discussion: http://discord.8b8t.me\nwebsite: https://www.8b8t.me\nThese are the only official 8b8t websites and contacts\n"


#configs for priority queue tablist
HEADERPRIORITY: "\n&18builders&98tools\n\n&67b7t is full\nPosition in queue: &l<position>\n&6Estimated time: &l<wait>\n"

FOOTERPRIORITY: "\n   &6You have priority queue status please wait for an available slot on the server   \n\n&7contact: nate@xera.ca\n
discussion: http://discord.8b8t.me\nwebsite: https://www.8b8t.me\nThese are the only official 8b8t websites and contacts\n"