name: LeeesBungeeQueue
version: 5.1.2
api-version: 1.12
main: Leees.Bungee.Queue.Bukkit.Main
author: Nate Legault
authors: [Nate, Legault]
description: Bukkit companion plugin for LeeesBungeeQueue
website: https://www.xera.ca