name: LeeesBungeeQueue
version: 5.0.1
api-version: 1.17
main: Leees.Bungee.Queue.Bukkit.Main
author: Nate Legault
authors: [Nate, Legault]
description: Bukkit companion plugin for LeeesBungeeQueue
website: https://www.xera.ca