package Leees.Bungee.Queue.Bungee;

import java.util.List;

/**
 * Lang
 */
public class Lang {

    public static String SERVERISFULLMESSAGE, QUEUEPOSITION, JOININGMAINSERVER, QUEUEBYPASSPERMISSION,
            HEADER, FOOTER, POSITIONMESSAGEHOTBAR, QUEUESERVER, QUEUEPRIORITYPERMISSION, HEADERPRIORITY,
            FOOTERPRIORITY, REGEX, KICKMESSAGE, ADMINPERMISSION, ENABLEKICKMESSAGE, MAINSERVER, AUTHSERVER,
            ENABLEAUTHSERVER, SERVERDOWNKICKMESSAGE, SERVERPINGINFOENABLE, ALWAYSQUEUE, CUSTOMPROTOCOL,
            CONNECTTOQUEUEWHENDOWN,ENABLEMOTD, MOTD, ENABLERANDOMMOTD, ENABLEQUEUESERVERSLOTS;
    public static int MAINSERVERSLOTS,QUEUEMOVEDELAY, QUEUESERVERSLOTS;
    public static List<String> SERVERPINGINFO;
    public static List<String> RANDOMMOTDS;
}
